baseurl = "https://vigorous-jepsen-d86e6f.netlify.com"
title = "missmorenakos"
theme = "wild"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "kon"
    info = "kon info"
    description = "kon description"
    keywords = "kon keywords"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "Enter a text here."

    math = true
    custom_css = ["css/custom.css"]

    mainSections = ["education", "reviews", "general"]

# Menu links
[[menu.main]]
    name = "education"
    weight = 2
    url  = "/education/"
[[menu.main]]
    name = "reviews"
    weight = 3
    url  = "/reviews/"
[[menu.main]]
    name = "general"
    weight = 4
    url  = "/general/"
[[menu.main]]
    name = "quotes"
    weight = 5
    url = "/quotes/"
[[menu.main]]
    name = "vocabulary"
    weight = 6
    url = "/vocabulary/"
[[menu.main]]
    name = "about"
    weight = 7
    url = "/about/"
