baseurl = "https://missmorenakos.com"
title = "missmorenakos"
theme = "wild"
languagecode = "en"
defaultcontentlanguage = "en"

[pagination]
    pagerSize = 20

canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "kon"
    info = "kon info"
    description = "kon description"
    keywords = "kon keywords"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "Enter a text here."

    math = true
    custom_css = ["css/custom.css"]

    mainSections = ["education", "views", "geography", "did_you_know"]

# Menu links
[[menu.main]]
    name = "education"
    weight = 2
    url  = "/education/"
[[menu.main]]
    name = "views"
    weight = 4
    url  = "/views/"
[[menu.main]]
    name = "geography"
    weight = 5
    url = "/geography/"
[[menu.main]]
    name = "quotes"
    weight = 8
    url = "/quotes/"
[[menu.main]]
    name = "vocabulary"
    weight = 7
    url = "/vocabulary/"
[[menu.main]]
    name = "did you know"
    weight = 9
    url = "/did_you_know/"
